name: Go Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      
    - name: Build
      run: go build ./test/
    
    - name: Step to test go mod
      run: go mod download ./test/

    - name: Run the Tests
      run: go test -v ./test/
